name: floodpath
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/q.png
    - assets/images/contactp.png
    - assets/images/runin.png
    - assets/images/hotlines.png
    - assets/images/notif.png
    - assets/images/arlogo.png
    - assets/images/dropdown.png
    